// Mocks generated by Mockito 5.3.2 from annotations
// in adviser/test/0_data/repositories/advice_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:adviser/0_data/datasources/advice_remote_datasource.dart'
    as _i3;
import 'package:adviser/0_data/models/advice_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdviceModel_0 extends _i1.SmartFake implements _i2.AdviceModel {
  _FakeAdviceModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AdviceRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdviceRemoteDataSource extends _i1.Mock
    implements _i3.AdviceRemoteDataSource {
  @override
  _i4.Future<_i2.AdviceModel> getRandomAdviceFromApi() => (super.noSuchMethod(
        Invocation.method(
          #getRandomAdviceFromApi,
          [],
        ),
        returnValue: _i4.Future<_i2.AdviceModel>.value(_FakeAdviceModel_0(
          this,
          Invocation.method(
            #getRandomAdviceFromApi,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.AdviceModel>.value(_FakeAdviceModel_0(
          this,
          Invocation.method(
            #getRandomAdviceFromApi,
            [],
          ),
        )),
      ) as _i4.Future<_i2.AdviceModel>);
}
